export function renderReport(report){
 const data=JSON.stringify(report).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Texture size planner</title>
<style>body{font:15px system-ui;background:#f6f5f1;color:#202822;margin:0;padding:28px;max-width:1500px;margin:auto}h1{font-size:28px;margin:0 0 8px}p{line-height:1.5}input{padding:12px;border:1px solid #a8b2a5;border-radius:6px;width:min(560px,90%);font:inherit}table{width:100%;border-collapse:collapse;background:white;margin-top:20px}th,td{text-align:left;padding:12px;border-bottom:1px solid #ddd;vertical-align:top}th{position:sticky;top:0;background:#e1e9df}td small{display:block;max-width:360px;overflow-wrap:anywhere;color:#667166;margin-top:5px}button{font:inherit;border:0;background:none;color:#195938;padding:0;text-align:left;cursor:pointer;text-decoration:underline}.scroll{overflow:auto}#details{padding:20px;background:#eaf0e5;margin:20px 0}ul{line-height:1.6}.muted{color:#687267}</style>
<h1>Texture size planner</h1><p id="summary"></p><p>Suggested sizes preserve sampled detail from existing images. They are advisory; bake and delivery settings are unchanged. Screen-density requirements are shown separately and can be much larger for thin UV islands or close travel.</p>
<label for="filter">Find a texture, room, or source file</label><p><input id="filter" type="search" placeholder="e.g. hall-trim, basement, room-lighting"></p><p id="count" class="muted"></p>
<div class="scroll"><table><thead><tr><th>Texture / file</th><th>Source</th><th>Suggested</th><th>Detail error<br><small>RMS / p95</small></th><th>Screen density<br><small>Rest / travel / close-up edge</small></th><th>Samples</th></tr></thead><tbody id="rows"></tbody></table></div>
<section id="details" hidden></section><h2>Assumptions and limits</h2><ul id="limits"></ul>
<script>const report=${data};
const el=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
const size=s=>s?s.width+' × '+s.height:'Unmeasured';
const number=n=>n==null?'—':Math.ceil(n).toLocaleString();
document.getElementById('summary').textContent=report.textures.length+' textures · '+report.stats.cameraViews+' camera views · '+report.stats.rays.toLocaleString()+' depth-tested rays · target DPR 2';
report.limitations.forEach(t=>document.getElementById('limits').append(el('li',t)));
function details(t){const panel=document.getElementById('details');panel.replaceChildren(el('h2',t.name||t.id),el('p',t.path));panel.hidden=false;panel.append(el('p','Strict density requirement: '+number(t.p99RequiredEdge)+' px at p99; '+number(t.maxRequiredEdge)+' px worst case.'));const list=el('ul','');for(const o of t.objects.slice(0,15))list.append(el('li',o.name+' — '+number(o.maxRequiredEdge)+' px; '+o.limitingView));panel.append(list);panel.scrollIntoView({behavior:'smooth',block:'nearest'});}
function update(){const filter=document.getElementById('filter').value.toLowerCase(),textures=report.textures.filter(t=>(t.name+' '+t.path).toLowerCase().includes(filter)),body=document.getElementById('rows');body.replaceChildren();document.getElementById('count').textContent=textures.length+' matching textures';for(const t of textures){const row=el('tr',''),name=el('td',''),button=el('button',t.name||t.id);button.onclick=()=>details(t);name.append(button,el('small',t.path));row.append(name,el('td',t.currentSize.join(' × ')),el('td',size(t.recommended)),el('td',t.detailEstimate?t.detailEstimate.rms+' / '+t.detailEstimate.p95:'—'),el('td',['rest','travel','closeup'].map(k=>number(t.contexts[k]?.p99RequiredEdge)).join(' / ')),el('td',number(t.samples)));body.append(row);}}
document.getElementById('filter').addEventListener('input',update);update();</script></html>`;
}
